config/routes.rb
Rails.application.routes.draw do
 	root 'pages#index'

 	resources :pages, only: [:index]
 	resources :inventory, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
require 'roo'

class Inventory < ApplicationRecord
	
	validates :item_type, presence: true
	validates :sku, presence: true, uniqueness: true , format: {with: /[A-Z]{3}[0-9]{4}/}
	validates :Title, presence: true
	validates :serial_number, presence: true, uniqueness: true, format: {with: /[0-9]{15}/}
	validates :quantity, presence: true
	validates :price, presence: true
	validates :organization, presence: true
	validates :Length, presence: true
	validates :Breadth, presence: true
	validates :Height, presence: true
	validates :Weight, presence: true
	validates :description, presence: true
	validates :short_description, presence: true
	validates :asset_code, presence: true
	validates :grade, presence: true
	validates :category, presence: true
	validates :brand, presence: true

	def self.import(file)
		if File.extname(file.original_filename) == '.csv'
			puts "----------------------------inside csv"
			CSV.foreach(file.path, headers: true) do |row|
				puts row.inspect
				inventory = find_by_id(row["id"]) || new
				inventory.volume = row["Length"].to_f*row["Breadth"].to_f*row["Height"].to_f
				#inventory.volume = self.Length*self.Breadth*self.Height
				inventory.attributes = row.to_hash#.slice(*column_names)
				inventory.save
			end
		elsif File.extname(file.original_filename) == '.xls'
			puts "----------------------------inside xls"
			spreadsheet = open_spreadsheet(file)
			header = spreadsheet.row(1)
			header.push("volume")
			import_errors = []
			(2..spreadsheet.last_row).each do |i|
				r = spreadsheet.row(i)
				volume = r[7]*r[8]*r[9]
				r.push(volume)
				puts [header, r].transpose.inspect
				row = Hash[[header, r].transpose]
				puts row
				inventory = find_by_id(row["id"]) || new
				#inventory.volume = row["Length"]*row["Breadth"]*row["Height"]
				inventory.attributes = row.to_hash
				inventory.save
				row_error = {i => inventory.errors.full_messages}
				import_errors.push(row_error)
			end
		end
		puts import_errors
		return import_errors
	end

	def self.open_spreadsheet(file)
		case File.extname(file.original_filename)
		when ".csv" then Csv.new(file.path, packed: nil, file_warning: :ignore)
		when ".xls" then Roo::Excel.new(file.path)
		when ".xlsx" then Roo::Excelx.new(file.path, packed: nil, file_warning: :ignore)
		else raise "Unknown file type: #{file.original_filename}"
		end
	end

	def self.to_csv(attributes = column_names, options = {})
		CSV.generate(options) do |csv|
			csv.add_row attributes
    		all.each do |inventory|
      			csv.add_row inventory.attributes.values_at(*attributes)
    		end
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController

	def new
	end

	def create
		params[:file].inspect
		@inventories = Inventory.all
		respond_to do |format|
			format.html { @import_errors = Inventory.import(params[:file])}

			#redirect_to root_path, notice: "Inventory imported."
			format.csv { send_data @inventories.to_csv }
			format.xls { send_data @inventories.to_csv(["serial_number", "volume"],col_sep: "\t") }
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/inventory/create.html.erb
<h3>The following errors prevented from upload:</h3>
<% @import_errors.each do |row_error| %>
<% puts row_error.values.inspect %>
<% keys = row_error.keys %>
<%= "In row number "+ keys[0].to_s + (row_error.values)[0].to_s%>
<br/>
<%end%>

app/views/inventory/new.html.erb
<h2>Import File</h2>
<%= form_tag inventory_index_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Import"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileImportExport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= button_to "Upload New File",  new_inventory_path, method: :get %>
<%= button_to "Download CSV file",  inventory_index_path(format: "csv") %>
<%= button_to "Download XLS file",  inventory_index_path(format: "xls") %>